### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by tttiago** [benrutter/Shades#4]
First of all, the project seems very dope as it allows to generate beautiful images.
However, I ran in some issues while going through the Handy Guide on the GitHub README (and also the description in PyPi).
It seems that the parameter ```noise_fields``` no longer exists, which was not updated accordingly in the PyPi description.
Also, in the example using ```shades.SwirlOfShades``` on GitHub, I presume ```noise_field``` should be updated to ```swirl_field```, but even then I ran into the error "color must be int or tuple".

**Comment by benrutter** [comment]
Thanks and woops! Cheers for spotting this - a couple of the parameter names changed moving into v. 1 to make stuff clearer, I'll update now.

Will take a look at the 'color must be int or tuple' error (sounds like a problem of ordering the swirl of shades lookup parameter, if you've got the code that caused the error please do post it up here!)

**Comment by benrutter** [comment]
Thanks again for raising - think this is all sorted now (raised another issue for the swirl bug (#6) just in case it comes up again.

The issue was caused by the swirl passing back 'None' where a color isn't appropriate. There had been error handling her previously I think from a messy 'try' loop, which I'd taken out without realising the impact.

Now, the abstract shade object won't make a point on the canvas if there isn't a color return for the determine_shade method, which should make hacking around a lot easier as well.

Added in some unit testing as well to capture if this happens again, plus ammended the documentation.

All released up to pip as v1.1 so updating library should fix this.
